import for_loop_capital_letter_A as A
import for_loop_capital_letter_B as B
import for_loop_capital_letter_C as C
import for_loop_capital_letter_D as D
import for_loop_capital_letter_E as E
import for_loop_capital_letter_F as F
import for_loop_capital_letter_G as G
import for_loop_capital_letter_H as H
import for_loop_capital_letter_I as I
import for_loop_capital_letter_J as J
import for_loop_capital_letter_k as K
import for_loop_capital_letter_L as L
import for_loop_capital_letter_M as M
import for_loop_capital_letter_N as N
import for_loop_capital_letter_O as O
import for_loop_capital_letter_P as P
import for_loop_capital_letter_Q as Q
import for_loop_capital_letter_R as R
import for_loop_capital_letter_S as S
import for_loop_capital_letter_T as T
import for_loop_capital_letter_U as U
import for_loop_capital_letter_V as V
#import for_loop_capital_letter_W as W
import for_loop_capital_letter_X as X
import for_loop_capital_letter_Y as Y
import for_loop_capital_letter_Z as Z
